### ISSUE TITLE
Desarrollo Lógico

### ISSUE THREAD

**Issue by EdnaEspejo** [EdnaEspejo/Cifras-con-plastilina#9]
- [ ]  Base de datos
- [ ]  Alimentación base de datos
- [ ]  Servicios
- [ ]  Lógica para la conversión de unidades
